language: c
compiler: gcc

os:
  - osx
  - linux

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - lua5.2
      - liblua5.2-dev
  homebrew:
    packages: 
       - python3.7
       - lua
       - pcre

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew update; fi || true
  - pyenv global system 3.7 || true

env:
  matrix:
    - OPTS=""
    - OPTS="--enable-lua --enable-python"

script: ./configure --enable-version --enable-symlink --enable-getaddrinfo --enable-atcp --enable-gmcp --enable-option102 $OPTS && make
