language: c
compiler: gcc

os:
  - osx
  - linux

dist: bionic

sudo: false

python: 3.7

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - lua5.2
    - liblua5.2-dev
  homebrew:
    packages: 
    - python3.7
    - lua
    - pcre
    update: true

before_install:
  - pyenv global system 3.7 || true

env:
  matrix:
    - OPTS="--enable-lua --enable-python"

script: ./configure --enable-version --enable-symlink --enable-getaddrinfo --enable-atcp --enable-gmcp --enable-option102 $OPTS && make
